# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 921cedca5f88bfaa2187c84d9eda27808a7676a96160170bad61cadc38c9355e7518f665dbec44b6b45f4e5197db20cc9c0d86c04d977f4431c3cad0076a9c63

test:
  secret_key_base: 3c3d56abbdce76de36256f0864b361134c147c476acfd903e6fc22c68ce056da4904e85b0d84cd245a4f817d58e305e290a26de613e43d6818f5dc6dde30ab1e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
